forum/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('register', views.register_view, name='register'),
    path('create/category', views.create_category_view, name='create_category'),
    path('delete/category/<int:pk>', views.delete_category_view, name='delete_category'),
    path('update/category/<int:pk>', views.update_category_view, name='update_category'),
    path('topics/<int:pk>', views.topic_list_view, name='topics'),
    path('create/topic/<int:pk>', views.topic_create_view, name='create_topic'),
    path('topic/posts/<int:pk>', views.topic_posts_view, name='topic_posts'),
    path('create/post/<int:pk>', views.create_post_view, name='create_post'),
]

forum/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('forum.core.urls')),
    path('', include('django.contrib.auth.urls')),
]

forum/core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinLengthValidator
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


def get_or_create_deleted():
    """ Get deleted user  """
    return User.objects.get_or_create(name='Erased')[0]


class Category(models.Model):
    """ Forum category model """
    name = models.CharField(_('Category name'), max_length=16, validators=[MinLengthValidator(3)])
    order_number = models.PositiveSmallIntegerField(_('Order number'), default=0)

    class Meta:
        """ Meta class """
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['-order_number']

    def __str__(self):
        return self.name


class Topic(models.Model):
    """ Topic model """
    name = models.CharField(_('Topic'), max_length=128, validators=[MinLengthValidator(12)])
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(_('Active'), default=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, blank=False, null=True)

    class Meta:
        """ Meta class """
        verbose_name = _('Topic')
        verbose_name_plural = _('Topics')
        ordering = ['-created_at']

    def __str__(self):
        return slugify(self.name)


class Post(models.Model):
    """ Post model """
    text = models.TextField(_('Text'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, blank=False, null=False)
    author = models.ForeignKey(User, on_delete=models.SET(get_or_create_deleted), null=True, blank=False)

    class Meta:
        """ Meta class """
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ['created_at']

forum/core/forms.py
""" Forms """
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from .models import Category, Topic, Post


class CreateCategoryForm(ModelForm):
    """ Create category form """
    class Meta:
        """ Meta class """
        model = Category
        fields = ['name', 'order_number']


class TopicForm(ModelForm):
    """ Create topic form """
    class Meta:
        """ Meta class """
        model = Topic
        fields = ['name']


class PostForm(ModelForm):
    """ Create post form """
    class Meta:
        """ Meta class """
        model = Post
        fields = ['text']


class RegisterForm(UserCreationForm):
    """ User registration form """
    first_name = forms.CharField(max_length=30, required=False, help_text="Optional.")
    last_name = forms.CharField(max_length=30, required=False, help_text="Optional.")
    email = forms.EmailField(max_length=128, help_text="Required.")

    class Meta:
        """ Meta class """
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

forum/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DeleteView, FormView, ListView, UpdateView
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _
from .forms import CreateCategoryForm, RegisterForm, TopicForm, PostForm
from .mixins import SuperUserMixin
from .models import Category, Topic, Post


class IndexView(ListView):
    """ Index view """
    model = Category
    template_name = "index.html"


index_view = IndexView.as_view()


class CreateCategoryView(LoginRequiredMixin, SuperUserMixin, SuccessMessageMixin, CreateView):
    """ Create Category view """
    model = Category
    form_class = CreateCategoryForm
    template_name = "create_category.html"
    success_url = reverse_lazy('core:index')
    success_message = _("Category successfully created")


create_category_view = CreateCategoryView.as_view()


class DeleteCategoryView(LoginRequiredMixin, SuperUserMixin, SuccessMessageMixin, DeleteView):
    """  Delete category view """
    model = Category
    template_name = "delete_category.html"
    success_url = reverse_lazy('core:index')
    success_message = _("Category successfully deleted")


delete_category_view = DeleteCategoryView.as_view()


class UpdateCategoryView(LoginRequiredMixin, SuperUserMixin, SuccessMessageMixin, UpdateView):
    """ Update category view """
    model = Category
    form_class = CreateCategoryForm
    template_name = "create_category.html"
    success_url = reverse_lazy('core:index')
    success_message = _("Category successfully updated")


update_category_view = UpdateCategoryView.as_view()


class TopicListView(ListView):
    """ List of topics from specified categories """
    model = Topic
    template_name = "topic_list.html"
    paginate_by = 20

    def get_queryset(self):
        """ Override queryset """
        category_pk = self.kwargs['pk']
        return Topic.objects.filter(category_id=category_pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        """ Extend get context data """
        context = super(TopicListView, self).get_context_data(object_list=object_list, **kwargs)
        context['category'] = Category.objects.get(id=self.kwargs['pk'])
        return context


topic_list_view = TopicListView.as_view()


class TopicCreateView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    """ Create new topic """
    model = Topic
    form_class = TopicForm
    model2 = Post
    form_class2 = PostForm
    template_name = "create_topic.html"
    success_message = _("Topic created with success")
    success_url = reverse_lazy("core:index")

    def get_context_data(self, **kwargs):
        """ Extend default context """
        context = super(TopicCreateView, self).get_context_data(**kwargs)
        context['form2'] = self.form_class2()
        return context

    def post(self, request, *args, **kwargs):
        """ Extend post method """
        response = super(TopicCreateView, self).post(request, *args, **kwargs)
        form = self.form_class({'name': request.POST['name']})
        form2 = self.form_class2({'text': request.POST['text']})

        if form.is_valid() and form2.is_valid():
            with transaction.atomic():
                new_topic = self.model(name=request.POST['name'], category_id=self.kwargs['pk'])
                new_topic.save()
                first_post = self.model2(text=request.POST['text'], topic=new_topic, author=request.user)
                first_post.save()
            return redirect(self.success_url)

        return render(request, self.template_name, {'form': form, 'form2': form2})


topic_create_view = TopicCreateView.as_view()


class TopicPostsView(ListView):
    """ List of posts from topic """
    model = Post
    template_name = "topic_posts.html"
    form_class = PostForm
    paginate_by = 20

    def get_queryset(self):
        """ Override queryset """
        topic_pk = self.kwargs['pk']
        return Post.objects.filter(topic_id=topic_pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        """ Extend get context data """
        context = super(TopicPostsView, self).get_context_data(object_list=object_list, **kwargs)
        context['topic'] = Topic.objects.get(id=self.kwargs['pk'])
        context['form'] = self.form_class()
        return context


topic_posts_view = TopicPostsView.as_view()


class CreatePostView(LoginRequiredMixin, CreateView):
    """ Create new post by authenticated user """
    model = Post
    form_class = PostForm
    success_message = _("Post created with success")

    def get(self, *args, **kwargs):
        """ Override method """
        return redirect(
            reverse('core:topic_posts', kwargs=kwargs)
        )

    def post(self, request, *args, **kwargs):
        """ Override method """
        form = self.form_class({'text': request.POST['text']})
        if not form.is_valid():
            messages.error(request, _("Incorrect data in post form!"))
            return redirect(
                reverse('core:topic_posts', kwargs=kwargs)
            )
        post = self.model(text=request.POST['text'], topic_id=kwargs['pk'], author=request.user)
        post.save()
        messages.success(request, self.success_message)
        return redirect(
            reverse('core:topic_posts', kwargs=kwargs)
        )


create_post_view = CreatePostView.as_view()


class RegisterView(SuccessMessageMixin, CreateView):
    """ Create new user """
    form_class = RegisterForm
    success_url = reverse_lazy('core:index')
    template_name = "registration/register.html"
    success_message = _("User successfully created")


register_view = RegisterView.as_view()

forum/core/templates/base.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% load bootstrap4 static i18n %}

<!-- Overwrite page title -->
{% block bootstrap4_title %}{% trans 'Python Academy Forum' %}{% endblock %}

<!-- Overwrite js extra panel -->
{% block bootstrap4_extra_head %}
    {% bootstrap_javascript jquery='full' %}
{% endblock %}

<!-- Overwrite place before content -->
{% block bootstrap4_before_content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Brand and toggle get grouped for better mobile display -->
    <a class="navbar-brand" href="{% url 'core:index' %}">{% trans 'Python Academy Forum' %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdow-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% trans 'Profile' %} {{ request.user }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="profileDropdown">
                        <a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">{% trans 'Change password' %}</a>
                    </div>
                </li>
            {% else %}
                <li class='nav-item {% if "logout" in request.path %} active {% endif %}'>
                    <a class="nav-link" href="{% url 'login' %}">{% trans 'Login' %}</a>
                </li>
                <li class='nav-item'>
                    <a class="nav-link" href="{% url 'core:register' %}">{% trans 'Register' %}</a>
                </li>
            {% endif %}
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>
{% endblock %}

{% block bootstrap4_content %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

{% block bootstrap4_after_content %}
<!--  Greate place for footer -->
{% endblock %}

forum/core/templates/create_category.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button _("Save") button_type="submit" button_class="btn btn-primary" %}
                <a href="{% url 'core:index' %}" class="btn btn-light">{% trans 'Cancel' %}</a>
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button _("Save") button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
                <a href="{% url 'core:index' %}" class="btn btn-light btn-lg btn-block">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

forum/core/templates/create_topic.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_form form2 %}
            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary" %}
                <a href="{% url 'core:index' %}" class="btn btn-warning">{% trans 'Cancel' %}</a>
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
                <a href="{% url 'core:index' %}" class="btn btn-warning btn-lg btn-block">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

forum/core/templates/delete_category.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>{% blocktrans with name=category.name %}Are you sure you want delete {{ name }}{% endblocktrans %}</h1>
            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button _("Delete") button_type="submit" button_class="btn btn-danger" %}
                <a href="{% url 'core:index' %}" class="btn btn-light">{% trans 'Cancel' %}</a>
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button _("Delete") button_type="submit" button_class="btn btn-danger btn-lg btn-block" %}
                <a href="{% url 'core:index' %}" class="btn btn-light btn-lg btn-block">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

forum/core/templates/index.html
{% extends 'base.html' %}

{% load bootstrap4 static i18n %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
          <div class="card-header">
              <div class="float-left">
                {% trans 'Categories' %}
              </div>
            {% if user.is_superuser %}
                <div class="float-right">
                    <a href="{% url 'core:create_category' %}" class="badge badge-success">{% trans 'Create new category' %}</a>
                </div>
            {% endif %}
          </div>
          <ul class="list-group list-group-flush">
            {% if object_list %}
                {% for category in object_list %}
                    <li class="list-group-item"><a href="{% url 'core:topics' category.pk %}">{{ category.name }}</a>
                        {% if user.is_superuser %}
                        <p class="float-right">
                            <a href="{% url 'core:delete_category' category.pk %}" class="badge badge-danger">{% trans 'Delete' %}</a>
                            <a href="{% url 'core:update_category' category.pk %}" class="badge badge-info">{% trans 'Edit' %}</a>
                        </p>
                        {% endif %}
                    </li>
                {% endfor %}
            {% else %}
              <li class="list-group-item">{% trans 'No categories' %}</li>
            {% endif %}
          </ul>
        </div>
    </div>
</div>
{% endblock %}

forum/core/templates/topic_list.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card mt-4">
          <div class="card-header">
              <div class="float-left">
                {{ category.name }}
              </div>

            <div class="float-right">
                <a href="{% url 'core:create_topic' category.pk %}" class="badge badge-success">{% trans 'Create new topic' %}</a>
            </div>
          </div>
          <ul class="list-group list-group-flush">
            {% if page_obj %}
                {% for topic in page_obj %}
                    <li class="list-group-item">
                        <a href="{% url 'core:topic_posts' topic.pk %}">{{ topic.name }}</a>
                    </li>
                {% endfor %}
            {% else %}
              <li class="list-group-item">{% trans 'No topics' %}</li>
            {% endif %}
          </ul>
        </div>
        <div class="pagination justify-content-center mt-4">
            {% bootstrap_pagination page_obj %}
        </div>
    </div>
</div>
{% endblock %}

forum/core/templates/topic_posts.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<div class="row">
    <div class="col">
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand">{{ topic.name }}</a>
        </nav>
        {% if object_list %}
            {% for post in page_obj %}
                <div class="card mt-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.author.username }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{% trans 'Created at:' %}{{ post.created_at }}{% if post.updated_at %}| {% trans 'Updated at:' %}{{ post.updated_at }}{% endif %}</h6>
                        <p class="card-text">{{ post.text }}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <li class="list-group-item">{% trans 'No posts' %}</li>
        {% endif %}
    </div>
</div>
{% if request.user.is_authenticated %}
<div class="row">
    <div class="col">
        <form class="form" method="post" action="{% url 'core:create_post' topic.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary" %}
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
            </div>
        </form>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col">
        <div class="pagination justify-content-center mt-4">
            {% bootstrap_pagination page_obj %}
        </div>
    </div>
</div>
{% endblock %}